-- schema and tables to be created for the subscription processor datasink
CREATE SCHEMA IF NOT EXISTS APPLICATION;

CREATE TABLE IF NOT EXISTS APPLICATION.V2_2_SUBSCRIBER(
	ID 				INT 			NOT NULL PRIMARY KEY,
	CERTIFICATE 	BINARY 			NOT NULL,
	TARGET_HOST		VARCHAR(255)	NOT NULL,
	TARGET_PORT		INT				NOT NULL
);

CREATE TABLE IF NOT EXISTS APPLICATION.V2_2_SITUATION_DATA_FILTER(
	ID 				INT 			NOT NULL,
	END_TIME		TIMESTAMP 		NOT NULL,
	TYPE			VARCHAR(255)	NOT NULL,
	TYPE_VALUE		INT				NOT NULL,
	REQUEST_ID		INT				NOT NULL,
	NW_LAT			NUMBER,
	NW_LON			NUMBER,
	SE_LAT			NUMBER,
	SE_LON			NUMBER,
	
	CONSTRAINT SUBSCRIBER_ID_FK FOREIGN KEY(ID) REFERENCES APPLICATION.V2_2_SUBSCRIBER(ID)
);